#!/usr/bin/env python3
# Writes OrblitSrgbTables.inc: the sRGB transfer function as hexadecimal
# double constants. See that file for why constants rather than pow() at
# start-up.
#
#   python3 make_srgb_tables.py > OrblitSrgbTables.inc
from decimal import Decimal, getcontext

getcontext().prec = 50


def decode(c):
    """IEC 61966-2-1: the linear value of an sRGB-encoded c in [0, 1]."""
    if c <= Decimal('0.04045'):
        return c / Decimal('12.92')
    return ((c + Decimal('0.055')) / Decimal('1.055')) ** Decimal('2.4')


print("""// The sRGB transfer function as constants. Generated by make_srgb_tables.py;
// do not edit.
//
// kSrgbToLinear[i] is the linear value of the 8-bit sRGB code i. The
// thresholds are the linear values where the encoded value crosses i + 0.5,
// so the 8-bit code of a linear value is the number of thresholds at or
// below it. Computed to fifty digits and printed as hexadecimal doubles,
// which is the point: a table computed at start-up goes through the
// platform's pow(), and pow() is not required to round the same way on
// macOS, glibc and MSVC. Constants are the same bytes everywhere, so a cooked
// texture is too.
""")
print("static const double kSrgbToLinear[256] = {")
for i in range(256):
    print("  %s," % float(decode(Decimal(i) / Decimal(255))).hex())
print("};")
print()
print("static const double kSrgbThresholds[255] = {")
for i in range(255):
    print("  %s," % float(decode((Decimal(i) + Decimal('0.5')) / Decimal(255))).hex())
print("};")
